### ISSUE TITLE
PayU.startPayment doesn't invoke the payment screen

### ISSUE THREAD

**Issue by SlitheryMender** [synclovisdevs/react-native-payu#2]
Hi,

I've followed the instruction steps and when I invoke startPayment, the code doesn't go further and is stuck waiting for Promise to resolve or reject and there is no change on the screen too.

Data sent to startPayment - 
{"amount": 90, "curl": "", "email": "xxxxx@gmail.com", "firstname": "Name", "furl": "", "hash": "", "key": "", "merchantID": "", "phone": "+91xxxxxxxxx", "productInfo": "Payment for order XXJO9B", "surl": "", "txnid": "IIUJKW", "udf1": "XXJO9B"}

Where am I going wrong here?

React Native version 0.63

I'm testing on Android.

**Comment by SlitheryMender** [comment]
Updated data with correct keys : 
{"amount": 90, "email": "", "failedUrl": "", "firstName": "", "hash": "", "isSandox": true, "key": "", "merchantId": "", "phone": "+91xxxxxxxx", "productName": "Payment for order SOASBR", "successUrl": "", "txnId": "JQN6DH", "udf1": "SOASBR"}


Response : 
Error: Request failed with status code 500
createError@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:157920:26
settle@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:157910:25
handleLoad@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:157810:15
dispatchEvent@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:32641:31
setReadyState@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:31791:27
__didCompleteResponse@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:31622:29
emit@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:5849:42
__callFunction@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:5035:36
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4767:31
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4989:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4766:21
callFunctionReturnFlushedQueue@[native code]

**Comment by SlitheryMender** [comment]
I figured out that it was issue with the Key and Salt. 

I got to know that we need a different set of Key and Salt for the Sandbox and the Web Merchant Key and Salt won't work with the Native SDKs for PayU.

**Comment by swaroopaillinda** [comment]
@SlitheryMender I have key and merchent id  they are working fine in web applications
but when i am ruuning in my ios or android its showing key is invalid message
as u said we need seperate key if so how to genrate them in payu website
Can you please help me as its very important
